### PR TITLE
Add `keep.meta` parameter to `ligerToSeurat`

### PR DESCRIPTION
**Pull request by samuel-marsh**
Hi LIGER team,

Just another quick PR.  This PR would add additional parameter to the `seuratToLiger` function that allows for moving additional metadata information (besides nGene, nUMI, and dataset) to the newly created Seurat Object.  I set to `FALSE` by default to keep functionality equivalent to current function.

Thanks,
Sam

p.s. Also tagging @mojaveazure here as representative from Seurat team.  I realize you guys are super busy with Seurat especially with release of 4.0 but if you or someone else has a second to check out the PR and make sure I've got things correct in terms of adding the existing metadata from LIGER object to the Seurat meta.data slot that would be great!  Tagged you as you've contributed to LIGER before but please feel free to pass off to someone else on team depending on your availability.
Thanks so much!
Sam

### CODE REVIEW

**Comment by mojaveazure** [comment]
This looks good to me from a Seurat perspective; thanks Sam!

**Comment by samuel-marsh** [comment]
Excellent! Thanks for the double check Paul!

**Comment by samuel-marsh** [comment]
Hi Welch Lab/LIGER team,

Just wanted to ping on this PR and see if it could be merged soon?  Easiest for reproducibility if it's part of package.

Thanks!
Sam

**Comment by samuel-marsh** [comment]
Closing this as devs have not commented in 2 years.

**Comment by cgao90** [comment]
Hi Sam,

Sorry for missing out this PR as well as the late response. Thank you very much for your time and effort into help improving LIGER. 

This `keep.meta` feature is helpful and we'd like to incorporate it. However, I notice you have removed this modification from your repo in the latest commit. Would you like to open another PR at you convenience? or we can add it from our end. Thanks again!

Best,

**Comment by samuel-marsh** [comment]
Hi @cgao90 

yes sorry I was working on another PR to resubmit with this one too but then got sidetracked.  I’ll re add and push this week.

Thanks so much!!

**Comment by samuel-marsh** [comment]
closing this as it's now part of liger 2.0.0

**Pull request closed without merging**
